pub const QUERIES: &[(i32, &str)] = &[
    (1, include_str!("../sql/1.sql")),
    (2, include_str!("../sql/2.sql")),
    (3, include_str!("../sql/3.sql")),
    (4, include_str!("../sql/4.sql")),
    (5, include_str!("../sql/5.sql")),
    (6, include_str!("../sql/6.sql")),
    (7, include_str!("../sql/7.sql")),
    (8, include_str!("../sql/8.sql")),
    (9, include_str!("../sql/9.sql")),
    (10, include_str!("../sql/10.sql")),
    (11, include_str!("../sql/11.sql")),
    (12, include_str!("../sql/12.sql")),
    (13, include_str!("../sql/13.sql")),
    (14, include_str!("../sql/14.sql")),
    (15, include_str!("../sql/15.sql")),
    (16, include_str!("../sql/16.sql")),
    (17, include_str!("../sql/17.sql")),
    (18, include_str!("../sql/18.sql")),
    (19, include_str!("../sql/19.sql")),
    (20, include_str!("../sql/20.sql")),
    (21, include_str!("../sql/21.sql")),
    (22, include_str!("../sql/22.sql")),
];
